services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    secrets:
      - wp_user_login
      - wp_admin_login
      - wp_user_pass
      - wp_admin_pass
      - wp_user_email
      - wp_admin_email
      - db_pass
      - db_login
    env_file:
      - .env
    volumes:
      - db-volume:/var/lib/mysql
    networks:
      - dock-net
    restart: on-failure

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    secrets:
      - wp_user_login
      - wp_admin_login
      - wp_user_pass
      - wp_admin_pass
      - wp_user_email
      - wp_admin_email
      - db_pass
      - db_login
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - wp-volume:/var/www/html
    networks:
      - dock-net
    restart: on-failure

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    secrets:
      - wp_user_login
      - wp_admin_login
      - wp_user_pass
      - wp_admin_pass
      - wp_user_email
      - wp_admin_email
      - db_pass
      - db_login
    ports:
      - 443:443
    env_file:
      - .env
    depends_on:
      - wordpress
    volumes:
      - wp-volume:/var/www/html
    networks:
      - dock-net
    restart: on-failure

volumes:
  wp-volume:
    driver: local
    name: wp-volume
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/wordpress
  db-volume:
    driver: local
    name: db-volume
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/mariadb

networks:
  dock-net:
    name: dock-net
    driver: bridge

secrets:
  wp_user_login:
    file: ../secrets/wp_user_login.txt
  wp_user_pass:
    file: ../secrets/wp_user_pass.txt
  wp_user_email:
    file: ../secrets/wp_user_email.txt
  wp_admin_login:
    file: ../secrets/wp_admin_login.txt
  wp_admin_pass:
    file: ../secrets/wp_admin_pass.txt
  wp_admin_email:
    file: ../secrets/wp_admin_email.txt
  db_login:
    file: ../secrets/db_login.txt
  db_pass:
    file: ../secrets/db_pass.txt